[package]
name = "faze-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
faze.workspace = true
ratatui.workspace = true
crossterm.workspace = true
